apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: adp-backend-template-dotnet-dev
  title: "ADP Backend Template Dotnet DEV"
  description: "Template to support rapid delivery of microservices for ADP Platform. It contains the configuration needed to deploy a simple dotnet web API to the Azure Kubernetes Platform."
  tags:
    - dotnet
    - aks
    - backend
spec:
  owner: ccts-adp
  type: backend
  parameters:
    - $yaml: ./parameters.yaml
    - $yaml: ../parameters/git-repository.yaml
    - $yaml: ../parameters/ci-cd.yaml
  steps:
    - $yaml: ./run-template.yaml
    - id: publish
      name: Publish
      action: publish:zip

  output:
    links:
      - title: Download
        url: ${{ steps.publish.output.dataUri }}
        icon: github
