#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"
# Guarantee clean environment
docker compose down -v
# Ensure container images are up to date
docker compose up --build
