apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: defra
  title: DEFRA
  description: UK government department responsible for safeguarding our natural environment, supporting our food & farming industry, and sustaining a thriving rural economy.
  links:
    - url: https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs/
      title: Website

spec:
  type: organization
  profile:
    displayName: DEFRA
    picture: https://avatars.githubusercontent.com/u/5528822?s=200&v=4
  children: [environment-agency, animal-plant-health-agency, rural-payments-agency, natural-england, marine-management-organisation, core-defra]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: defra-arms-length-bodies
  description: Arms Length Bodies under the DEFRA organisation.
spec:
  targets:
    - ./arms-length-bodies/environment-agency.yaml
    - ./arms-length-bodies/animal-plant-health-agency.yaml
    - ./arms-length-bodies/rural-payments-agency.yaml
    - ./arms-length-bodies/natural-england.yaml
    - ./arms-length-bodies/marine-management-organisation.yaml
    - ./arms-length-bodies/core-defra.yaml
