#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"
# Guarantee clean environment
docker-compose -f docker-compose.yaml -f docker-compose.zap.yaml -p ${{ values.service_name | replace("'", "'\''") }}-zap-scan down -v
# Run ZAP scan
docker-compose -f docker-compose.yaml -f docker-compose.zap.yaml run --rm zap-baseline-scan
