apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ffc-demo-service-bus
  description: Messaging service for the FFC Demo Service
  tags:
    - azure-service-bus
spec:
  type: message-service
  owner: "group:default/fcp-payments"
  system: ffc-demo-service
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ffc-demo-claim-queue
  description: Claims message queue
  tags:
    - azure-service-bus
    - queue
spec:
  type: message-queue
  owner: "group:default/fcp-payments"
  system: ffc-demo-service
  dependsOn: 
    - "resource:default/ffc-demo-service-bus"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ffc-demo-calculation-queue
  description: Calculation message queue
  tags:
    - azure-service-bus
    - queue
spec:
  type: message-queue
  owner: "group:default/fcp-payments"
  system: ffc-demo-service
  dependsOn:
    - "resource:default/ffc-demo-service-bus"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ffc-demo-schedule-topic
  description: Schedules message topic
  tags:
    - azure-service-bus
    - topic
spec:
  type: message-topic
  owner: "group:default/fcp-payments"
  system: ffc-demo-service
  dependsOn:
    - "resource:default/ffc-demo-service-bus"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ffc-demo-payment-topic
  description: Payments message topic
  tags:
    - azure-service-bus
    - topic
spec:
  type: message-topic
  owner: "group:default/fcp-payments"
  system: ffc-demo-service
  dependsOn:
    - "resource:default/ffc-demo-service-bus"
