apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.repo_project_slug}}
spec:
  type: ${{ values.component_type }}
  lifecycle: ${{ values.component_lifecycle }}
  owner: ${{values.owner | dump}}
  {%- if values.system %}
  system: ${{ values.system }}
  {%- endif %}
  