apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  {% if values.description -%}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.repo_project_slug}}
    dev.azure.com/project: ${{ values.ado_project_name }}
    dev.azure.com/build-definition: ${{values.project_name}}
    sonarqube.org/project-key: ${{values.project_name}}
    grafana/dashboard-selector: "folderTitle == 'Managed Prometheus'"
    backstage.io/kubernetes-id: ${{values.project_name}}
  links:
    - url: https://github.com/${{values.repo_project_slug}}
      title: GitHub Repository
      icon: github
    - url: https://dev.azure.com/defragovuk/${{ values.ado_project_name }}/
      title: Azure DevOps Project
      icon: project
    - url: https://sonarcloud.io/project/overview?id=${{values.project_name}}
      title: SonarCloud Analysis
      icon: check
    - url: https://snyk.io/test/github/DEFRA/${{values.project_name}}
      title: Snyk Analysis
      icon: policy
    - url: https://portal.azure.com/defradev.onmicrosoft.com
      title: Azure Portal - Defra Dev
      icon: cloud
    - url: https://portal.azure.com/Defra.onmicrosoft.com
      title: Azure Portal - Defra
      icon: cloud
spec:
  type: backend
  lifecycle: ${{ values.component_lifecycle }}
  owner: ${{values.owner | dump}}
  {% if values.system -%}
  system: ${{ values.system }}
  {%- endif %}
